### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by vprus**
- Reduce overdraw by removing the window background when no longer needed
- Correct the position of face icon

### CODE REVIEW

**Comment by saulmm** [comment]
Thanks!. Agree with the overdrawing issue, nice point. Regarding the margin-bottom change, there is a small jump on my device from the background  to the start position of the face image. Maybe to get the exact value of the status bar or using fitSystemWindows at the activity with the center face icon animation could do the trick. What do you think?

**Comment by vprus** [comment]
I think the most reliable solution for demo would be to request
SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN, I'll update the pull request shortly.

**Comment by saulmm** [comment]
Sounds good!

**Comment by vprus** [comment]
Added another commit to the pull request, please take a look.

**Comment by saulmm** [comment]
I'm still appreciating a small jump when the activity content is shown. What do you think about dynamically set a padding/margin-top on the imageview instead using the fullscreen feature?. What device are you using to test?

**Comment by vprus** [comment]
I was testing on Galaxy S6, which does not have navigation bar, and so failed to set the second flag. I've pushed a fix for that. I have also implemented a variant with dynamic padding, see https://github.com/vprus/onboarding-examples-android/commit/60191b9e21f4931cb163420b7d0e568dafe2e496, but it's considerably more tricky.

**Comment by vprus** [comment]
Have you had the time to look at the most recent state of the pull request?

**Comment by saulmm** [comment]
Thanks for your patience & sorry for the delay, looks better now! Is interesting your solution overloading the `onWindowFocusChanged` method.

Thanks for your contribution!

**Comment by vprus** [comment]
Thanks for merging and for coming up with these cool animations in the
first place! Regarding starting animation on focus, it might be better
since at this point all UI is fully laid out, thought I could not see any
difference in this case.

**Pull request merged**
